Recognizer/Recognizer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

Recognizer/app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),

    path('removeSource/<int:id>/', views.removeSource, name='removeSource'),
    path('sources/', views.sources, name='sources'),

    path('video_feed', views.videoFeed, name="videoFeed"),

    path('removeTarget/<int:id>/', views.removeTarget, name='removeTarget'),
    path('targets/', views.targets, name='targets'),

    path('encounters/<int:encDay>/', views.dayEncounter, name='encounterDay'),
]

Recognizer/app/models.py
from django.db import models

# Create your models here.
class Source(models.Model):
    ip_adress = models.CharField(max_length=15)
    video_feed_name = models.CharField(max_length=50)
    name = models.CharField(max_length=50)

    def __str__(self):
        return "{} ({})".format(self.name, self.ip_adress)

class Target(models.Model):
    target_name = models.CharField(max_length=150)
    target_photo = models.BinaryField()
    target_recognizer_photo = models.BinaryField()
    targer_reco_vector = models.BinaryField()
    target_photo_info=models.CharField(max_length=150)
    def __str__(self):
        return self.target_name

class Encounter(models.Model):
    enc_time = models.DateTimeField() # use timezone.now()!!!
    enc_source = models.ForeignKey(Source, on_delete=models.DO_NOTHING)
    enc_target = models.ForeignKey(Target, on_delete=models.DO_NOTHING)

Recognizer/app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, StreamingHttpResponse
from django.urls import reverse
from django.views import generic

from .camera import VideoCamera
from .models import Source, Target

import re

class SourceDetailView(generic.DetailView):
    model = Source
    #template_name = 'app/sourceDetail.html'

class SourceListView(generic.ListView):
    model = Source
    #template_name = 'app/sourceDetail.html'
    #context_object_name = 'source_list'


# Create your views here.
def index(request):
    sourceList = Source.objects.all()
    targetsList = Target.objects.all()
    context = {'source_list': sourceList,
               'target_list': targetsList }
    return render(request, 'app/index.html', context)

def dayEncounter(request, **kwargs):
    response = "Encountered target in day %s"
    return HttpResponse(response % kwargs['encDay'])

def removeSource(request, **kwargs):
    instance = Source.objects.get(id=kwargs['id'])
    instance.delete()
    return HttpResponseRedirect(reverse('app:index'))

def selectSource(request, **kwargs):
    instance = Source.objects.get(id=kwargs['id'])
    return HttpResponseRedirect(reverse('app:index'))

def sources(request, **kwargs):
    sourceList = Source.objects.all()
    context = {'source_list': sourceList}
    return render(request, 'app/sourceContent.html', context)

def removeTarget(request, **kwargs):
    instance = Target.objects.get(id=kwargs['id'])
    instance.delete()
    return HttpResponseRedirect(reverse('app:index'))
def targets(request, **kwargs):
    targetList = Target.objects.all()
    context = {'target_list': targetList}
    return render(request, 'app/targetContent.html', context)

def gen(camera):
    while True:
        frame = camera.getFrame()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n'+frame+b'\r\n\r\n')

def videoFeed(request):
    return StreamingHttpResponse(gen(VideoCamera()), content_type='multipart/x-mixed-replace; boundary=frame')

Recognizer/app/templates/app/addSourceModal.html
<div class="modal fade" id="addSourceModel" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Добавление нового источника</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body">
            <label for="ipAdress" class="form-label">IP адрес</label>
            <input id="ipAdress" type="text" name = "ip" class="form-control"><br>

            <label for="descr" class="form-label">Наименование</label>
            <input id="descr" type="text" name = "descr" class="form-control"><br>

            <label for="feedName" class="form-label">Имя потока</label>
            <input id="feedName" type="text" name = "feed" class="form-control"><br>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button id="addSourceBtn" onclick="addSourceClick()" type="button" class="btn btn-primary" data-bs-dismiss="modal">Сохранить изменения</button>
      </div>
    </div>
  </div>
</div>

Recognizer/app/templates/app/addTargetModal.html
<div class="modal fade" id="addTargetModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Добавление новой цели наблюдения</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
      </div>
      <div class="modal-body">
          <label for="targetName" class="form-label">Имя цели</label>
          <input id="targetName" type="text" name = "ip" class="form-control"><br>
          <label for="formFile" class="form-label">Фотография цели</label>
          <input id="formFile" class="form-control" type="file" onchange="openNewPhoto()">
          <img id="photo" src="" class="img-fluid" alt="Responsive image">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        <button id="addTargetBtn" onclick="addTargetClick()" type="button" class="btn btn-primary" data-bs-dismiss="modal">Сохранить изменения</button>
      </div>
    </div>
  </div>
</div>

Recognizer/app/templates/app/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">
    <script src="{% static 'app/js/recognizer.js' %}"></script>
    <script src="{% static 'app/js/bootstrap.bundle.min.js' %}"></script>
    <title>{% block title %}OBSERVER v0.1 Наблюдение.{% endblock %}</title>
</head>
<body>
{% block body %}
    <div id="root" class="container-fluid">
        <div class="row">
            <div id = "encounter" class="col-md-4">
              {% block encounter %} Encounter {% endblock %}
            </div>

            <div id="source-target" class="col-md-4">
                <div id="source">
                  {% block sources %} Source {% endblock %}
                </div>
                <div id="target">
                  {% block targets %} Target {% endblock %}
                </div>
            </div>
            <div id="video" class="col-md-4">
                  {% block live %} Live {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

Recognizer/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block sources %}
<div class="overflow-y-auto">
    <table class="table table-dark table-hover table-sm align-middle caption-top">
        <caption>Источники трансляции:</caption>
        <thead>
            <tr>
                <th scope="col" >IP адрес</th>
                <th scope="col">Наименование</th>
                <th scope="col">Канал трансляции</th>
            </tr>
        </thead>
        <tbody class="table-group-divider" id="sourceTable">
            {% include 'app/sourceContent.html' %}
        </tbody>
    </table>
    <div class="d-grid gap-2">
        <button type="button" data-bs-toggle="modal" data-bs-target="#addSourceModel" class="btn btn-primary">Добавить источник</button>
    </div>
    {% include 'app/addSourceModal.html' %}
</div>
{% endblock %}

{% block targets %}
<caption>Цели поиска:</caption>
<div id="targetsTable" class="overflow-y-auto" style="height:600px;">
{% include 'app/targetContent.html' %}
</div>
<div class="d-grid gap-2">
    <button type="button" data-bs-toggle="modal" data-bs-target="#addTargetModal" class="btn btn-primary">Добавить цель наблюдения</button>
</div>
{% include 'app/addTargetModal.html' %}
{% endblock %}

{% block encounter %}
Encounted
{% endblock %}

{% block live %}
<caption>Трансляция:</caption>
<canvas id="canvasLive" width="800" height="800"></canvas>
{% endblock %}

Recognizer/app/templates/app/sourceContent.html
<div id="sourceBtns">
{% for source in source_list %}
<tr>
    <td >{{source.ip_adress}}</td>
    <td>{{source.name}}</td>
    <td>{{source.video_feed_name}}</td>
    <td><a class="btn btn-danger btn-sm" href="{% url 'app:removeSource' source.id %}">Удалить</a></td>
    <td><button id="startSourceBtn{{ source.id }}" class="btn btn-primary btn-sm" onclick="startSourceClick({{ source.id }})">Включить</button></td>
</tr>
{% endfor %}
</div>

Recognizer/app/templates/app/targetContent.html
{% for target in target_list %}
<div class="card" id="id{{target.id}}">
    <div class="row">
        <div class="col-md-6">
            <img src="data:image/jpg;base64,{{target.target_photo.decode}}" class="img-fluid">
        </div>
        <div class="col-md-6">
            <img src="data:image/jpg;base64,{{target.target_recognizer_photo.decode}}" class="img-fluid">
        </div>
    </div>
    <div class="card-body">
        <h5 class = "card-title">{{target.target_name}}</h5>
        <p class="card-text"></p>
        <a class="btn btn-danger btn-sm" href="{% url 'app:removeTarget' target.id %}">Удалить</a>
    </div>
</div>
{% endfor %}